name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ env.NVMRC }}
      - name: Install packages
        run: npm i
      - name: Linter
        run: npm run lint
      - name: Tests
        run: npm run test
      - name: Prettier
        run: npm run check-prettier
      - name: TypeScript
        run: npm run check-types
